#!/usr/bin/env ruby

# author: dohzya
# licence: GPLv3

def here_dir where
  str = "#{File.file?(where) ? File.dirname(where) : where}"
  def str./ other
    "#{self}/#{other}"
  end
  puts str
  str
end

here = here_dir __FILE__
require here/"lib/dls.rb"

